config/routes.rb
Rails.application.routes.draw do
  resources :notes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "notes#index"
  get "home/trash_em"
  get "home/trash_em_all"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /trash_em
  def trash_em
    @trash_em = Note.where(completed: true).destroy_all
    redirect_to root_url, notice: "All Completed Note was successfully deleted."
  end

    # GET /trash_em_all
    def trash_em_all
      @trash_em_all = Note.all.destroy_all
      redirect_to root_url, notice: "All Note was successfully deleted."
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @new_note = Note.new
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to root_url, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to root_url, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy!

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to "Todo List", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
<%= form_with(model: note, class: "d-flex") do |form| %>
      <form class="d-flex">
        <%= form.text_field :description, class: 'form-control me-2' %>
        <%= form.submit "Add Todo", class: "btn btn-outline-success", type: 'submit' %>
      </form>
<% end %>
    </div>
  </div>
</nav>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todo Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar", note: @new_note %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_flash.html.erb
<% flash.each do |name, message|%>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= content_tag(:div, message) %>
    </div>
<% end %>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>
  
  <div class="mb-3 form-check">
    <%= form.label :completed, class: 'form-check-label' %>
    <%= form.check_box :completed, class: 'form-check-input' %>
  </div>

  <div>
    <%= form.submit "Update Todo", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<% if note.completed %>
<tr class="table-success">
  <td class="striketrhough"><%= link_to note.description, edit_note_path(note) %></td>
  <td>
    <center><%= link_to "Delete", note, class: 'btn btn-outline-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></center>
  </td>
</tr>
<% else %>
<tr>
  <td><%= link_to note.description, edit_note_path(note) %></td>
  <td>
    <center><%= link_to "Delete", note, class: 'btn btn-outline-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %></center>
  </td>
</tr>
<% end %>

app/views/notes/index.html.erb
<%= render 'flash' %>

<% content_for :title, "Notes" %>

<table class="table table-bordered">
  <tbody>
    <% @notes.each do |note| %>
      <%= render note %>
    <% end %>
  </tbody>

  </table>

<%= link_to "Delete Completed Items", home_trash_em_path, class:'btn btn-danger',data: {
    turbo_method: :get,
    turbo_confirm: "Are you sure?"
  } %>

  <%= link_to "Delete All Items", home_trash_em_all_path, class:'btn btn-danger',data: {
    turbo_method: :get,
    turbo_confirm: "Are you sure?"
  } %>